Feature
ntzwilly/portfolio pull request #1
Opened 2021-06-02 17:35 UTC by ntzwilly

## Project requirements:

For this project, I have to use the HTML&CSS linter and build a mobile version of two sections.

## The 2 sections  for this project are:

- The toolbar (or header): Toolbar

- The headline section (right after the header): Headline

2021-06-02 18:30 UTC, Shaher-11 reviewed
## Status:  Invalid:no_entry:
## Hello @ntzwilly 

This Code Review Request will be marked as invalid in your Dashboard because the Linters are not set up properly on Github.
You can use this  [linters guide](https://github.com/microverseinc/linters-config/tree/master/html-css) to make sure everything is working properly.
Please make the necessary changes and submit another code review request once you are ready! :slightly_smiling_face:.

2021-06-02 20:53 UTC, MahmoudBakr23 requested changes
Hello @ntzwilly😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Linter is well-configured. 💯 
- Descriptive PR summary, a README file, and commit messages. 💯 

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄


 ## Required Changes ♻️

- [ ] Please make sure to write a short, descriptive PR headline instead of the default "Feature" one.
It's so important to be as much as detailed about your work as possible.

_Also, please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Please check the **OPTIONAL** comments under the review._

## **IMPORTANT NOTE**
_Please do not push or commit any changes after you submit a code review request because it might cause many conflicts in the code review process._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 20:53 UTC, MahmoudBakr23 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Please fix the MIT link because it's broken.
Kindly keep in mind that it's very important to make your README professional and with no mistakes because such a very small one might leave a bad impression on future viewers.

2021-06-02 20:53 UTC, MahmoudBakr23 commented on index.html
> +      <div class="circle"><a href="#"><img src="images/git.svg" alt="git-logo"></a></div>
- [ ] **OPTIONAL** I can see your great work on the Semantic HTML. But, don't you think it'd be better to not wrap everything inside a `<div>` tag. i.e. line 22 wouldn't be better if it's just the `<h1>` tag with the `class="title"`! what do you think?

2021-06-02 20:53 UTC, MahmoudBakr23 commented on styles.css
> +
- [ ] Please remove this extra blank line here to keep your code clean and organized.
Kindly remember that you shouldn't add blank lines or indentations without a reason.

2021-06-02 20:53 UTC, MahmoudBakr23 commented on styles.css
> +  color: #acb7c3;
- [ ] Please make sure to follow the given [design template](https://www.figma.com/file/NWVDbyHlxMtZO5VX92hpM1/Microverse-Student-Project-1-(Copy)) for best practices and better results.
Kindly use the same color of the hamburger button as it is in the design.
Design Template
![Screenshot](https://user-images.githubusercontent.com/47625407/120547899-fe8b2a80-c3f1-11eb-9e92-1e2df5dea4ff.png)
Your Design
![Screenshot1](https://user-images.githubusercontent.com/47625407/120547938-08149280-c3f2-11eb-88c3-1c929c602018.png)

2021-06-02 20:53 UTC, MahmoudBakr23 commented on styles.css
> +}
- [ ] Please attach the background image in the headline section as in the given design.

_Please look at the comment above about following the design template._

2021-06-02 20:53 UTC, MahmoudBakr23 commented on styles.css
> +}
- [ ] Kindly use the same font-weight and color for this paragraph as the given design.

_Please look at the comment above about following the design template._

2021-06-02 20:53 UTC, MahmoudBakr23 commented on styles.css
> +}
- [ ] Kindly use the same font-weight and color for this text as the given design.

_Please look at the comment above about following the design template._

2021-06-02 20:53 UTC, MahmoudBakr23 commented on styles.css
> +  color: #acb7c3;
- [ ] For the logo and the hamburger button. Kindly use the same padding and margins as the given design.

_Please look at the comment above about following the design template._

2021-06-02 20:53 UTC, MahmoudBakr23 commented on index.html
> +    </div>
- [ ] Please notice that this is supposed to be a link (`<a>` tag). Kindly fix that according to the [Semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp).

2021-06-02 20:53 UTC, MahmoudBakr23 commented on index.html
> +      <div class="circle"><a href="#"><img src="images/git.svg" alt="git-logo"></a></div>
- [ ] Kindly notice that this is a social links list. So, according to the [Semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp). It'd be way too better if you used the `<ul>`, `<li>`, and finally `<a>` tags for those social links to be a list.

2021-06-02 20:53 UTC, MahmoudBakr23 commented on index.html
> +      <div class="logo-container"><img src="images/Logo-placeholder.svg" alt="logo"></div>
- [ ] Please keep in mind that the logo is considered the main referral to the website. So, it'd be nicer if it has a link `<a>` tag to make the navigation easier for the user.

2021-06-02 20:53 UTC, MahmoudBakr23 commented on index.html
> +      <div class="hamburger-container"><i class="fas fa-bars"></i></div>
- [ ] Kindly make sure that the hamburger button is supposed to have a `<nav>` tag. Please work on that issue too.

2021-06-03 08:18 UTC, ntzwilly commented on README.md
> +This project is [MIT](./MIT.md) licensed.
Thank you for your suggestion. I am looking for the one that is not broken.

2021-06-03 08:26 UTC, ntzwilly commented on styles.css
> +}
Thank you. I am still working on making the background image.

2021-06-03 09:36 UTC, ntzwilly commented on styles.css
> +  color: #acb7c3;
Changes the button's color

2021-06-03 09:54 UTC, ntzwilly commented on index.html
> +      <div class="circle"><a href="#"><img src="images/git.svg" alt="git-logo"></a></div>
Done

2021-06-03 10:11 UTC, ntzwilly commented on index.html
> +      <div class="hamburger-container"><i class="fas fa-bars"></i></div>
Done

2021-06-03 10:16 UTC, ntzwilly commented on index.html
> +      <div class="circle"><a href="#"><img src="images/git.svg" alt="git-logo"></a></div>
Thank you. It is better this way. I removed the unnecessary Divs.

2021-06-03 10:54 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @ntzwilly    ! :wave: :wave:

#### You have done really well in implementing the requirements.
- You used proper GitHub Flow ✔️ 
- Your linter checks are all passing ✔️ 
- Your README and PR message are descriptive ✔️ 

 However, there are changes required for you to make in order for this project to be approved. 
- - -

### **Recommended** ♻️
- [ ] Kindly refer to the design template and update your project to fit the requirements.

_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.

- N/A


_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 1 more review as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-03 10:54 UTC, Temmarie commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] As requested by the previous code reviewer, kindly fix the broken MIT link.

2021-06-03 10:54 UTC, Temmarie commented on styles.css
> +
- [ ] I see you removed the blank line at the bottom of the page, however, the previous reviewer was referring to this  ⬆️  line at the top of the page. Kindly remove it.

2021-06-03 10:54 UTC, Temmarie commented on styles.css
> +  color: #acb7c3;
- [ ] I see that you've made a few changes as required but your project still doesn't follow the given template design. You are missing:
- the background image,
- the colours used are lighter and faded compared to the design,
- and you have a typographical error here(It should say `Glad`, not `Grad`).
Kindly revisit the [template](https://www.figma.com/file/NWVDbyHlxMtZO5VX92hpM1/Microverse-Student-Project-1-(Copy)) and make the necessary changes.

2021-06-03 10:54 UTC, Temmarie commented on styles.css
> +}
- [ ] As required by the previous code reviewer and as I mentioned above, kindly refer to the design template and make the corresponding changes.

2021-06-03 10:54 UTC, Temmarie commented on styles.css
> +}
- [ ] Kindly use the same paddings and margins as the given design.

2021-06-03 10:54 UTC, Temmarie commented on index.html
> +    <h4 class="header-2">LET’S CONNECT</h4>
- [ ] As mentioned by the previous code reviewer, this is supposed to be a link tag. Kindly use the appropriate semantic `a` tag for it.

2021-06-03 10:54 UTC, Temmarie commented on index.html
> +      <div class="logo-container"><img src="images/Logo-placeholder.svg" alt="logo"></div>
- [ ] Kindly make the logo a link `a` tag, as it is the main referral to the website. It also makes navigation a lot easier for the user and improves the overall aesthetics of the website.

2021-06-03 14:41 UTC, ntzwilly commented on styles.css
> +  color: #acb7c3;
- I added the background image.
- The colours are matching the design now
- Corrected the typographical error

2021-06-03 14:57 UTC, MahmoudBakr23 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
Great work

2021-06-03 14:58 UTC, MahmoudBakr23 commented on index.html
> +      <div class="circle"><a href="#"><img src="images/git.svg" alt="git-logo"></a></div>
Keep up 🥰

2021-06-03 17:10 UTC, ntzwilly commented on README.md
> +This project is [MIT](./MIT.md) licensed.
The link is now working

2021-06-03 17:12 UTC, ntzwilly commented on styles.css
> +
I removed the black line

2021-06-03 17:17 UTC, ntzwilly commented on styles.css
> +}
I used the paddings and margins from the design

2021-06-03 17:19 UTC, ntzwilly commented on styles.css
> +
I removed extra blank

2021-06-03 18:14 UTC, ntzwilly commented on index.html
> +    <h4 class="header-2">LET’S CONNECT</h4>
Applied the link tag

2021-06-03 18:18 UTC, ntzwilly commented on index.html
> +      <div class="logo-container"><img src="images/Logo-placeholder.svg" alt="logo"></div>
The logo is now a link

2021-06-03 18:33 UTC, MahmoudBakr23 approved these changes
Hi @ntzwilly 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 18:44 UTC, merged