Detail popup window
ntzwilly/portfolio pull request #13
Opened 2021-06-25 22:33 UTC by ntzwilly

# Project 8: Details modal
## Project requirements
### implement the following interactions:

- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
-  When the user clicks (or taps) the close (X) button, the popup disappears.
     - implement popups for both mobile and desktop screen sizes:
     - Mobile popup
- Stick to the design as much as possible (e.g., font, colors, images, tests, margins) using the templates in Figma.
- In order to associate each project with the popup window details, use a JavaScript array to store all of the information for all projects.
  - For each project, store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to the source.
  - Update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. All the HTML in that section is created when the page loads.
After that, implement the popup window.

2021-06-25 23:27 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
- No Linters error ✔️

## Aspects to improve ♻️

- [ ] Please, fix your image size on pop-ups, on mobile size isn't look a lot, but the image size affects the good design for the project, desktop size is something to improve too. I kindly invite you to work on that. 😄
- On desktop size, I couldn't see the close button or any kind of info, because the image is bigger than expected
- On mobile if you observe the top-right corner, the text and close button are together, this would be for image size too, I guess...

| mobile | desktop |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/20563252/123493606-9d1a3e00-d5e2-11eb-8a48-40138f60b178.png) | ![image](https://user-images.githubusercontent.com/20563252/123493641-b91ddf80-d5e2-11eb-9faf-947a836a938b.png) |

- [ ] Check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-25 23:27 UTC, vichuge commented on javascript/modal_generator.js
> +  console.log(modalContainer);
- [ ] As a good practice, it would be great if you delete the `console.log()` lines, this is a best practice that I invite you to follow. If you want to consult the [Js best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) 🐶

2021-06-25 23:27 UTC, vichuge commented on javascript/modal_handler.js
> +  console.log(e.srcElement.id);
- [ ] As a good practice, it would be great if you delete the `console.log()` lines, this is a best practice that I invite you to follow. If you want to consult the [Js best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) 🐶

2021-06-25 23:27 UTC, vichuge commented on javascript/modal_handler.js
> +    console.log(closeModal);
- [ ] As a good practice, it would be great if you delete the `console.log()` lines, this is a best practice that I invite you to follow. If you want to consult the [Js best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) 🐶

2021-06-25 23:27 UTC, vichuge commented on javascript/portfolio.js
> +  // console.log(portfolio);
- [ ] As a good practice, it would be great if you delete the `console.log()` lines, this is a best practice that I invite you to follow. If you want to consult the [Js best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) 🐶

2021-06-25 23:27 UTC, vichuge commented on javascript/portfolio.js
> +  //  console.log(works)
- [ ] As a good practice, it would be great if you delete the `console.log()` lines, this is a best practice that I invite you to follow. If you want to consult the [Js best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) 🐶

2021-06-26 06:25 UTC, ntzwilly commented on javascript/modal_generator.js
> +  console.log(modalContainer);
Thank you. This issue is now fixed

2021-06-26 06:26 UTC, ntzwilly commented on javascript/modal_handler.js
> +  console.log(e.srcElement.id);
I removed console.log()

2021-06-26 06:26 UTC, ntzwilly commented on javascript/modal_handler.js
> +    console.log(closeModal);
console.log(removed)

2021-06-26 06:26 UTC, ntzwilly commented on javascript/portfolio.js
> +  // console.log(portfolio);
I removed console.log()

2021-06-26 06:28 UTC, ntzwilly commented on javascript/portfolio.js
> +  //  console.log(works)
I removed console.log()

2021-06-26 07:16 UTC, DeliceLydia commented on javascript/modal_generator.js
> +  console.log(modalContainer);
Well addressed this!

2021-06-26 07:16 UTC, DeliceLydia commented on javascript/modal_handler.js
> +  console.log(e.srcElement.id);
Well done!

2021-06-26 07:17 UTC, DeliceLydia commented on javascript/modal_handler.js
> +    console.log(closeModal);
Well done!

2021-06-26 07:17 UTC, DeliceLydia commented on javascript/portfolio.js
> +  // console.log(portfolio);
Addressed this!

2021-06-26 07:17 UTC, DeliceLydia commented on javascript/portfolio.js
> +  //  console.log(works)
Well  done!

2021-06-26 07:19 UTC, DeliceLydia approved these changes
# Status: Approved🎉 🎉 

Hi @ntzwilly , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-26 08:12 UTC, merged