Create desktop version
ntzwilly/portfolio pull request #5
Opened 2021-06-10 10:29 UTC by ntzwilly

# Project 4: Desktop version

   Use media queries to make sure that the website displays correctly on desktop screens.

## Project requirements: 

- Use media queries in the CSS file to make the desktop version look like the template you selected.

- Use Grid and Flexbox in order to layout the elements on the page.

- No need to implement any functionality that requires JavaScript.

- Replicate the design as much as possible (e.g., font, colors, images, tests, margins) using the info from the Figma templates.

2021-06-10 12:05 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @ntzwilly and @Munsa1    ! :wave: :wave:

#### You have done really well in implementing the requirements.
- You used proper GitHub Flow ✔️ 
- Your linter checks are all passing ✔️ 
- Your README and PR message are descriptive ✔️ 

 However, there are changes required for you to make in order for this project to be approved. 

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. :smile:

- - -

### **Required Changes** ♻️
- [x] Kindly refer to the design in Figma and try to make the project as similar as possible to the template you have chosen.

_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 2 more reviews as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-10 12:05 UTC, Temmarie commented on index.html
> +          name="email"
- [ ] The background image here has some placement issues. Kindly fix it.

_Refer to my comments on the design above._

_See the images below for clarity._

**Original** | **Your clone**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/121521359-cfa02600-c9a8-11eb-9711-83c68ae4a1b6.png) | ![image](https://user-images.githubusercontent.com/49621279/121521390-dc247e80-c9a8-11eb-840e-92fc8903f69b.png)

2021-06-11 14:34 UTC, ntzwilly commented on index.html
>        </header>
Thank you for the review, this issue has been solved

2021-06-11 14:37 UTC, ntzwilly commented on index.html
>            <div class="logo-container">
I added the remaining sections to the main and used the images from the Figma template. Also used typography from Figma

2021-06-11 14:38 UTC, ntzwilly commented on index.html
> +          <li class="circle">
This issue is now solved

2021-06-11 14:39 UTC, ntzwilly commented on index.html
> +          name="email"
The background is now well placed

2021-06-11 15:23 UTC, Dipeshtwis commented on index.html
>        </header>
This issue was successfully addressed. :+1:

2021-06-11 15:26 UTC, Dipeshtwis commented on index.html
> +          <li class="circle">
This issue was successfully addressed. :+1:

2021-06-11 15:27 UTC, Dipeshtwis commented on index.html
> +          name="email"
This issue was successfully addressed. :+1:

2021-06-11 15:30 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @ntzwilly, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-11 15:31 UTC, Dipeshtwis commented on index.html
>            <div class="logo-container">
This issue was successfully addressed. :+1:

2021-06-12 09:56 UTC, merged