Portfolio mobile menu
ntzwilly/portfolio pull request #9
Opened 2021-06-21 15:23 UTC by ntzwilly

# Project 7: Mobile menu
## Project requirements
- Add the JavaScript linter.

- In mobile, implement the following features:

  - When the user clicks (or taps) the hamburger button, the mobile menu appears.
  
  - When the user clicks (or taps) the close (X) button, the mobile menu disappears.
  
  - When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.

2021-06-21 19:32 UTC, rloterh requested changes
# Changes Required! ♻️

Hi Abraham and Willy 👋 👋, I'm Robert, your reviewer for this PR.

I must commend you for the nice work done👏.  You nailed almost all of the specifications of this project right. There some necessary changes we need to implement to improve this project.

## Good points 👍
No Linters errors ✔️
Good use of HTML semantics ✔️


## Aspects to improve ♻️

_Check the comment(s) under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-21 19:32 UTC, rloterh commented on styles.css
>  @media screen and (min-width: 1024px) {
- [ ] Our design is appearing to be squashed when the breakpoint lower than **1024px**. 

Your design looks like this:
![shot3](https://user-images.githubusercontent.com/12745474/122813908-6df68a80-d2cb-11eb-9a97-ec484e729245.jpg)

We want to ensure that our design fits the full width of the browser/ media screen at current whatever the breakpoint lesser than desktop screens. Let's ensure to improve upon this to make our design fit nicely on a specific media screen.

2021-06-21 19:32 UTC, rloterh commented on index.html
> +        <nav class="header-nav-link">
- [ ] Your implementation of the mobile menu is nice! However, we want both our design and features to follow the provided [Figma template]() as closely as possible. Your design is missing some hover effects on the mobile menu.

Here's your design when the menu is hovered:
![shot2](https://user-images.githubusercontent.com/12745474/122816376-8ddb7d80-d2ce-11eb-984f-480f9a840c86.jpg)

Here's the original design for the same action:
![shot4](https://user-images.githubusercontent.com/12745474/122816858-25d96700-d2cf-11eb-82bd-56234098b31e.jpg)


Let's improve this by adding the hover effect to our menu items for mobile screen.

2021-06-22 11:02 UTC, ntzwilly commented on script.js
> +  burger.addEventListener('click', () => {
Thank you for your feedback. This issue is now fixed

2021-06-22 11:03 UTC, ntzwilly commented on styles.css
>  @media screen and (min-width: 1024px) {
I have made the required changes. The design fits now the full width

2021-06-22 11:25 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-22 12:56 UTC, merged